mybook/book/urls.py
from django.urls import path

from . import book_views
from .book_views import BookLV, BookCV, BookDV, BookUV, BookXV
from .user_view import UserCV, UserDV, UserLoginView, MyPageView, UserLogoutView

urlpatterns = [
    path(r'', book_views.main, name='index'),
    path('users/register', UserCV.as_view(), name='user-create'),
    path('users/<int:pk>', UserDV.as_view(), name='user-detail'),
    path('users/me', MyPageView.as_view(), name='mypage'),
    path('users/login', UserLoginView.as_view(), name='login'),
    path('users/logout', UserLogoutView.as_view(), name='logout'),
    path('books/', BookLV.as_view(), name='book-list'),
    path('books/<int:pk>/', BookDV.as_view(), name='book-detail'),
    path('books/add/', BookCV.as_view(), name='book-create'),
    path('books/<int:pk>/update/', BookUV.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', BookXV.as_view(), name='book-delete'),
]

mybook/mybook/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'', views.main),
    path(r'', include('book.urls')),
]

mybook/book/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.forms import forms
from django.urls import reverse


def limit_today_validator(date):
    import datetime
    if date > datetime.date.today():
        raise forms.ValidationError("오늘 날짜를 넘을 수 없습니다.")


class Book(models.Model):
    NOT_READ = '1'
    READING = '2'
    READ = '3'

    READ_STATUS = (
        (NOT_READ, '읽지않음'),
        (READING, '읽는중'),
        (READ, '읽음'),
    )

    READ_STATUS_COLOR = {
        NOT_READ: 'default',
        READING: 'info',
        READ: 'primary',
    }

    title = models.CharField(verbose_name='타이틀', max_length=100)
    contents = models.CharField(verbose_name='서평', max_length=300, null=True, blank=True)
    read_status = models.CharField(verbose_name='책 상태', max_length=1, choices=READ_STATUS,
                                   default=NOT_READ, blank=False)
    purchase_date = models.DateField(verbose_name='구매일', null=True,
                                     validators=[limit_today_validator])
    created = models.DateTimeField(verbose_name='등록일', auto_now_add=True)
    user = models.ForeignKey('User', verbose_name='사용자',
                             on_delete=models.CASCADE,
                             null=False, blank=False)

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk': self.pk})

    @property
    def read_status_class(self):
        return Book.READ_STATUS_COLOR[self.read_status]

    class Meta:
        verbose_name = 'book'
        verbose_name_plural = 'books'

        def __str__(self):
            return self.title


class UserManager(BaseUserManager):
    def create_user(self, email, name, nick_name=None, password=None):
        if not email:
            raise ValueError("User must have an email")

        user = self.model(email=email, name=name, nick_name=nick_name)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, name, password):
        user = self.model(email=email, name=name)
        user.set_password(password)
        user.is_admin = True
        user.save()


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, verbose_name='Email')
    name = models.CharField(max_length=20, verbose_name='이름')
    nick_name = models.CharField(max_length=20, verbose_name='닉네임', blank=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    @property
    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

        def __str__(self):
            return self.name

mybook/book/forms.py
from .models import User, Book
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='비밀번호 재입력', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'name')
        labels = {
            'email': 'Email',
            'name': '이름',
        }

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("입력하신 비밀번호가 일치 하지 않습니다.")

        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])

        if commit:
            user.save()

        return user


class UserChangeForm(forms.ModelForm):
    current_password = forms.CharField(label='비밀번호', widget=forms.PasswordInput, required=False)
    password = forms.CharField(label='변경 비밀번호', widget=forms.PasswordInput, required=False)
    password_confirm = forms.CharField(label='변경 비밀번호 확인', widget=forms.PasswordInput, required=False)


    class Meta:
        model = User
        fields = ('email', 'nick_name', 'name')

    def clean_current_password(self):
        current_password = self.data['current_password']

        if not current_password:
            return current_password


        email = self.cleaned_data['email']
        user = self._meta.model.objects.get(email=email)

        if not user.check_password(current_password):
            raise forms.ValidationError("현재 비밀번호가 일치 하지 않습니다.")


    def clean_password(self):
        current_password = self.data['current_password']
        password = self.cleaned_data['password']

        if not current_password:
            return None
        else:
            if not password:
                raise forms.ValidationError("변경할 비밀번호를 입력해주세요")

        return self.cleaned_data['password']


    def clean_password_confirm(self):
        current_password = self.data['current_password']
        password = self.data['password']
        password_confirm = self.cleaned_data['password_confirm']

        if not current_password:
            return None
        else:
            if password and password_confirm and password != password_confirm:
                raise forms.ValidationError("입력하신 비밀번호가 일치 하지 않습니다.")

        return self.cleaned_data['password_confirm']


    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data['password']

        if password is not None:
            print(user.name)
            user.set_password(password)

        if commit:
            user.save()
            return user


class UserLoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass


class BookCreateForm(forms.ModelForm):
    contents = forms.CharField(label='서평', required=False,
                               widget=forms.Textarea(
                                   attrs={'rows': 5, 'cols': 100}))
    purchase_date = forms.DateField(label='구매일', required=False,
                                    widget=forms.DateInput(
                                        attrs={'type': 'date'}))

    class Meta:
        model = Book
        fields = ['title', 'contents', 'user', 'purchase_date', 'read_status']


class BookForm(forms.ModelForm):
    contents = forms.CharField(label='서평', required=False,
                               widget=forms.Textarea(
                                   attrs={'rows': 5, 'cols': 100}))
    purchase_date = forms.DateField(label='구매일', required=False,
                                    widget=forms.DateInput(
                                        attrs={'type': 'date'}))

    class Meta:
        model = Book
        fields = ['title', 'contents', 'user', 'purchase_date', 'read_status']

mybook/book/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book
from .user_view import *


def main(request):
    return render(request, 'index.html')


# def book(request):
#     return render(request, 'book/book.html')


class BookLV(ListView):
    model = Book
    template_name = 'book/book.html'
    context_object_name = 'books'
    # paginate_by = 10  # 페이징


class BookDV(DetailView):
    model = Book
    template_name = 'book/book_detail.html'
    context_object_name = 'book'


class BookCV(CreateView):
    model = Book
    fields = ['title', 'contents', 'user']
    template_name = 'book/book_create.html'


class BookUV(UpdateView):
    model = Book
    fields = ['title', 'contents']
    template_name_suffix = '_update'


class BookXV(DeleteView):
    models = Book
    queryset = Book.objects.all()
    template_name = 'book/book_confirm_delete.html'
    success_url = reverse_lazy('book-list')

mybook/book/templates/book/book.html
{% extends 'base.html' %}
{% load book_extras %}

{% block content %}
  <div class="content-body">
    <div class="col-md-12">
      <div class="book-action-box">
        <div style="display: inline-block">
          <div class="mybook-message align-middle mr-3">
             <span class="mybook-message-unit">총</span><br>
            {{ books.count }}<span class="mybook-message-unit">권</span>
          </div>
         </div>
        {% for count in read_status_counts %}
          <div style="display: inline-block">
            <div class="mybook-message {{ count.read_status|get_read_status_colors }}-color align-middle mr-3">
               <span class="mybook-message-unit">{{ count.read_status|get_read_status_display }}</span><br>
              {{ count.count }}<span class="mybook-message-unit">권</span>
            </div>
          </div>
        {% endfor %}
        <div class="mybook-add-book-btn">
          <a href="{% url 'book-create' %}">
            <button type="button" class="btn btn-light book-add-btn">책 등록하기</button>
          </a>
        </div>
      </div>
    </div>

    {% for book in books %}
      <div class="col-md-4" style="float: left;">
        <div class="book-card">
          <a href="{{ book.get_absolute_url }}">
            <div class="card-body book-module">
              <p class="book-card-data column-title">{{ book.title }}</p>
              <p class="book-card-data column-text">{{ book.created|date:"Y-m-d" }}</p>
            </div>
          </a>
          <a href="">
            <div class="book-status-badge">
                <span class="badge badge-pill badge-{{ book.read_status_class }}">
                    {{ book.get_read_status_display }}
                </span>
            </div>
          </a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

mybook/book/templates/book/book_confirm_delete.htm
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

mybook/book/templates/book/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="content-body">
  <form action="{% url 'book-delete' book.id %}" method="post">{% csrf_token %}
    <div class="book-action-box">
        <p>"{{ book.title }}" 책을 삭제하시겠습니까?</p>
        <button type="submit" class="btn btn-danger"> 삭제</button>
        <a href="{% url 'book-update' book.id %}">
          <button type="button" class="btn btn-secondary">뒤로가기</button>
        </a>
    </div>
  </form>
</div>
{% endblock %}

mybook/book/templates/book/book_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="content-body">
  <form action="{% url 'book-create' %}" method="post">{% csrf_token %}
    <div class="form-group row">
      <label for="id_title" class="col-sm-2 col-form-label">타이틀</label>
      <div class="col-sm-10">
        {{ form.title|add_class:"form-control" }}
      </div>
    </div>
    <div class="form-group row">
      <label for="contents" class="col-sm-2 col-form-label">서평</label>
      <div class="col-sm-10">
        {{ form.contents|add_class:"form-control" }}
      </div>
    </div>
    <div class="form-group row">
      <label for="read_status" class="col-sm-2 col-form-label">책 상태</label>
      <div class="col-sm-10">
        {{ form.read_status|add_class:"form-control" }}
      </div>
    </div>
    <div class="form-group row">
      <label for="purchase_date" class="col-sm-2 col-form-label">구매일</label>
      <div class="col-sm-10">
        {{ form.purchase_date|add_class:"form-control" }}
        {{ form.purchase_date.errors }}
      </div>
    </div>
    <input type="hidden" name="user" id="id_user" class="form-control" value="{{ user.id }}">

    <div class="book-action-box">
      <input type="submit" class="btn btn-primary" value="완료" />
      <a href="{% url 'book-list' %}">
        <button type="button" class="btn btn-secondary">목록으로</button>
      </a>
    </div>

  </form>
</div>
{% endblock %}

mybook/book/templates/book/book_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="content-body">
  <div class="book-card-detail">
    <div class="card-body">
      <h3>{{ book.title }}</h3>
      <h6>{{ book.contents|linebreaks }}</h6>
      <div class="book-status-badge">
        <span class="badge badge-pill badge-{{ book.read_status_class }}">
            {{ book.get_read_status_display }}
        </span>
      </div>
      <p class="book-card-data column-text">구매일: {{ book.purchase_date|date:"Y-m-d" }} </p>
      <p class="book-card-data column-text">닉네임: {{ book.user.nick_name }} </p>
      <p class="book-card-data column-text">등록일: {{ book.created|date:"Y-m-d" }} </p>
    </div>
  </div>
  <div class="book-action-box">
    <a href="{% url 'book-update' book.id %}">
      <button type="button" class="btn btn-info">수정</button>
    </a>
    <a href="{% url 'book-list' %}">
      <button type="button" class="btn btn-secondary">목록으로</button>
    </a>
  </div>
</div>

{% endblock %}

mybook/book/templates/book/book_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
  <div class="content-body">
    <form action="{% url 'book-update' book.id %}" method="post">{% csrf_token %}
      <div class="form-group row">
        <label for="id_title" class="col-sm-2 col-form-label">타이틀</label>
        <div class="col-sm-10">
          {{ form.title|add_class:"form-control" }}
        </div>
      </div>
      <div class="form-group row">
        <label for="contents" class="col-sm-2 col-form-label">서평</label>
        <div class="col-sm-10">
          {{ form.contents|add_class:"form-control" }}
        </div>
      </div>
      <div class="form-group row">
        <label for="read_status" class="col-sm-2 col-form-label">책 상태</label>
        <div class="col-sm-10">
          {{ form.read_status|add_class:"form-control" }}
        </div>
      </div>
      <div class="form-group row">
        <label for="purchase_date" class="col-sm-2 col-form-label">구매일</label>
        <div class="col-sm-10">
          {{ form.purchase_date|add_class:"form-control" }}
          {{ form.purchase_date.errors }}
        </div>
      </div>
      <input type="hidden" name="user" id="id_user" class="form-control" value="{{ user.id }}">    <div class="book-action-box">

      <input type="submit" class="btn btn-primary" value="저장" />
      <a href="{% url 'book-delete' book.id %}?next={{ request.path|urlencode }}">
        <button type="button" class="btn btn-danger"> 삭제</button>
      </a>
      <a href="{{ book.get_absolute_url }}">
        <button type="button" class="btn btn-secondary">뒤로가기</button>
      </a>
    </div>
  </form>
  </div>
{% endblock %}

mybook/book/templates/book/user_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="content-body">
  <form action="{% url 'user-create' %}" method="post">{% csrf_token %}
  {% for field in form %}
    <div class="form-group row">
      <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
      <div class="col-sm-10">
          {{ field|add_class:"form-control"}}
          {{ field.errors }}
      </div>
    </div>
  {% endfor %}
    <div class="book-action-box">
      <input type="submit" class="btn btn-primary" value="완료" />
      <a href="{% url 'index' %}">
        <button type="button" class="btn btn-secondary">돌아가기</button>
      </a>
    </div>
  </form>
</div>

{% endblock %}

mybook/book/templates/book/user_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="content-body">
  <div class="book-card">
    <div class="card-body">
      <h3>{{ user.email }}</h3>
    </div>
  </div>
  <div class="user-action-box">

  </div>
</div>

{% endblock %}

mybook/book/templates/book/user_login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="content-body">
  <form action="{% url 'login' %}" method="post">{% csrf_token %}
  {% for field in form %}
    <div class="form-group row">
      <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
      <div class="col-sm-10">
          {{ field|add_class:"form-control"}}
          {{ field.errors }}
      </div>
    </div>
  {% endfor %}
    <div class="book-action-box">
      <input type="submit" class="btn btn-primary" value="로그인" />
      <a href="{% url 'user-create' %}">
        <button type="button" class="btn btn-secondary">회원가입</button>
      </a>
      <a href="{% url 'index' %}">
        <button type="button" class="btn btn-secondary">돌아가기</button>
      </a>
    </div>
  </form>
</div>

{% endblock %}

mybook/book/templates/book/user_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="content-body">
  <form action="{% url 'mypage' %}" method="post">{% csrf_token %}
  {% for field in form %}
    <div class="form-group row">
      <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
      <div class="col-sm-10">
          {{ field | add_class:"form-control"}}
          {{ field.errors }}
      </div>
    </div>
  {% endfor %}
    <div class="book-action-box">
      <input type="submit" class="btn btn-primary" value="완료" />
      <a href="{% url 'logout' %}">
        <button type="button" class="btn btn-secondary">로그아웃</button>
      </a>
    </div>
  </form>
</div>

{% endblock %}